name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Flutter 3.29.2 (Dart 3.7.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable
          cache: true

      - name: Check Installed Versions
        run: |
          flutter --version
          dart --version

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install Dependencies and Build Web
        run: |
          cd personal_website
          flutter clean
          flutter pub get
          flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./personal_website/build/web
          publish_branch: gh-pages
          force_orphan: true